import { ProductData } from 'ts/interfaces';

const productsLayout: ProductData[] = [
  {
    id: '1',
    brand: 'Cougar',
    name: 'COUGAR 700K Evo',
    type: 'механическая',
    price: '120',
    quantity: '5',
    colorEffect: 'RGB',
  },
  {
    id: '2',
    brand: 'Cougar',
    name: 'COUGAR VANTAR',
    type: 'ножничная',
    price: '70',
    quantity: '10',
    colorEffect: 'многоцветная',
  },
  {
    id: '3',
    brand: 'HyperX',
    name: 'HyperX Alloy Elite 2',
    type: 'механическая',
    price: '130',
    quantity: '2',
    colorEffect: 'RGB',
  },
  {
    id: '4',
    brand: 'HyperX',
    name: 'HyperX Alloy Origins',
    type: 'механическая',
    price: '110',
    quantity: '7',
    colorEffect: 'RGB',
  },
  {
    id: '5',
    brand: 'HyperX',
    name: 'HyperX Alloy Core RGB',
    type: 'мембранная',
    price: '50',
    quantity: '7',
    colorEffect: 'RGB',
  },
  {
    id: '6',
    brand: 'Razer',
    name: 'Razer BlackWidow V3 Pro',
    type: 'механическая',
    price: '230',
    quantity: '1',
    colorEffect: 'RGB',
  },
  {
    id: '7',
    brand: 'Razer',
    name: 'Razer Huntsman V2',
    type: 'механическая',
    price: '250',
    quantity: '4',
    colorEffect: 'RGB',
  },
  {
    id: '8',
    brand: 'Razer',
    name: 'Razer Cynosa V2',
    type: 'мембранная',
    price: '60',
    quantity: '9',
    colorEffect: 'RGB',
  },
  {
    id: '9',
    brand: 'Razer',
    name: 'Razer Cynosa Lite',
    type: 'мембранная',
    price: '40',
    quantity: '6',
    colorEffect: 'RGB',
  },
  {
    id: '10',
    brand: 'MSI',
    name: 'MSI Vigor GK50 Low Profile',
    type: 'механическая',
    price: '90',
    quantity: '12',
    colorEffect: 'RGB',
  },
  {
    id: '11',
    brand: 'MSI',
    name: 'MSI Vigor GK71 SONIC',
    type: 'механическая',
    price: '110',
    quantity: '3',
    colorEffect: 'RGB',
  },
  {
    id: '12',
    brand: 'Razer',
    name: 'Razer Ornata V2',
    type: 'мембранная',
    price: '100',
    quantity: '8',
    colorEffect: 'многоцветная',
  },
  {
    id: '13',
    brand: 'Corsair',
    name: 'Corsair K63',
    type: 'механическая',
    price: '80',
    quantity: '12',
    colorEffect: 'красная',
  },
  {
    id: '14',
    brand: 'Cougar',
    name: 'COUGAR VANTAR AX',
    type: 'ножничная',
    price: '150',
    quantity: '6',
    colorEffect: 'RGB',
  },
  {
    id: '15',
    brand: 'ZET',
    name: 'ZET GAMING Dagger SE',
    type: 'механическая',
    price: '50',
    quantity: '2',
    colorEffect: 'красная',
  },
  {
    id: '16',
    brand: 'MSI',
    name: 'MSI Vigor GK20',
    type: 'мембранная',
    price: '30',
    quantity: '5',
    colorEffect: 'RGB',
  },
  {
    id: '17',
    brand: 'Corsair',
    name: 'Corsair K55 RGB PRO XT',
    type: 'мембранная',
    price: '70',
    quantity: '9',
    colorEffect: 'RGB',
  },
  {
    id: '18',
    brand: 'Corsair',
    name: 'Corsair K55 RGB',
    type: 'мембранная',
    price: '50',
    quantity: '1',
    colorEffect: 'RGB',
  },
  {
    id: '19',
    brand: 'Razer',
    name: 'Razer Huntsman Tournament Edition',
    type: 'механическая',
    price: '130',
    quantity: '1',
    colorEffect: 'RGB',
  },
  {
    id: '20',
    brand: 'MSI',
    name: 'MSI GK50 ELITE',
    type: 'механическая',
    price: '70',
    quantity: '11',
    colorEffect: 'RGB',
  },
  {
    id: '21',
    brand: 'HyperX',
    name: 'HyperX Alloy MKW100',
    type: 'механическая',
    price: '80',
    quantity: '5',
    colorEffect: 'RGB',
  },
  {
    id: '22',
    brand: 'Corsair',
    name: 'Corsair K60 RGB PRO',
    type: 'механическая',
    price: '90',
    quantity: '4',
    colorEffect: 'RGB',
  },
];

export default productsLayout;
