import { ProductData } from "../ts/interfaces";

export const data: ProductData[] = [
  {
    num: '1',
    brand: 'Cougar',
    name: 'COUGAR 700K Evo',
    type: 'механическая',
    price: '120',
    count: '5',
    colorEffect: 'RGB',
  },
  {
    num: '2',
    brand: 'Cougar',
    name: 'COUGAR VANTAR',
    type: 'ножничная',
    price: '70',
    count: '10',
    colorEffect: 'многоцветная',
  },
  {
    num: '3',
    brand: 'HyperX',
    name: 'HyperX Alloy Elite 2',
    type: 'механическая',
    price: '130',
    count: '2',
    colorEffect: 'RGB',
  },
  {
    num: '4',
    brand: 'HyperX',
    name: 'HyperX Alloy Origins',
    type: 'механическая',
    price: '110',
    count: '7',
    colorEffect: 'RGB',
  },
  {
    num: '5',
    brand: 'HyperX',
    name: 'HyperX Alloy Core RGB',
    type: 'мембранная',
    price: '50',
    count: '7',
    colorEffect: 'RGB',
  },
  {
    num: '6',
    brand: 'Razer',
    name: 'Razer BlackWidow V3 Pro',
    type: 'механическая',
    price: '230',
    count: '1',
    colorEffect: 'RGB',
  },
  {
    num: '7',
    brand: 'Razer',
    name: 'Razer Huntsman V2',
    type: 'механическая',
    price: '250',
    count: '4',
    colorEffect: 'RGB',
  },
  {
    num: '8',
    brand: 'Razer',
    name: 'Razer Cynosa V2',
    type: 'мембранная',
    price: '60',
    count: '9',
    colorEffect: 'RGB',
  },
  {
    num: '9',
    brand: 'Razer',
    name: 'Razer Cynosa Lite',
    type: 'мембранная',
    price: '40',
    count: '6',
    colorEffect: 'RGB',
  },
  {
    num: '10',
    brand: 'MSI',
    name: 'MSI Vigor GK50 Low Profile',
    type: 'механическая',
    price: '90',
    count: '12',
    colorEffect: 'RGB',
  },
  {
    num: '11',
    brand: 'MSI',
    name: 'MSI Vigor GK71 SONIC',
    type: 'механическая',
    price: '110',
    count: '3',
    colorEffect: 'RGB',
  },
  {
    num: '12',
    brand: 'Razer',
    name: 'Razer Ornata V2',
    type: 'мембранная',
    price: '100',
    count: '8',
    colorEffect: 'многоцветная',
  },
  {
    num: '13',
    brand: 'Corsair',
    name: 'Corsair K63',
    type: 'механическая',
    price: '80',
    count: '12',
    colorEffect: 'красная',
  },
  {
    num: '14',
    brand: 'Cougar',
    name: 'COUGAR VANTAR AX',
    type: 'ножничная',
    price: '150',
    count: '6',
    colorEffect: 'RGB',
  },
  {
    num: '15',
    brand: 'ZET',
    name: 'ZET GAMING Dagger SE',
    type: 'механическая',
    price: '50',
    count: '2',
    colorEffect: 'красная',
  },
  {
    num: '16',
    brand: 'MSI',
    name: 'MSI Vigor GK20',
    type: 'мембранная',
    price: '30',
    count: '5',
    colorEffect: 'RGB',
  },
  {
    num: '17',
    brand: 'Corsair',
    name: 'Corsair K55 RGB PRO XT',
    type: 'мембранная',
    price: '70',
    count: '9',
    colorEffect: 'RGB',
  },
  {
    num: '18',
    brand: 'Corsair',
    name: 'Corsair K55 RGB',
    type: 'мембранная',
    price: '50',
    count: '1',
    colorEffect: 'RGB',
  },
  {
    num: '19',
    brand: 'Razer',
    name: 'Razer Huntsman Tournament Edition',
    type: 'механическая',
    price: '130',
    count: '1',
    colorEffect: 'RGB',
  },
  {
    num: '20',
    brand: 'MSI',
    name: 'MSI GK50 ELITE',
    type: 'механическая',
    price: '70',
    count: '11',
    colorEffect: 'RGB',
  },
  {
    num: '21',
    brand: 'HyperX',
    name: 'HyperX Alloy MKW100',
    type: 'механическая',
    price: '80',
    count: '5',
    colorEffect: 'RGB',
  },
  {
    num: '22',
    brand: 'Corsair',
    name: 'Corsair K60 RGB PRO',
    type: 'механическая',
    price: '90',
    count: '4',
    colorEffect: 'RGB',
  },
];

export const optionsLayout: string[] = [
  'По названию (A-Z)',
  'По названию (Z-A)',
  'Сначала недорогие',
  'Сначала дорогие',
  'Максимальное количество',
  'Минимальное количество',
];

export const brandsLayout: string[] = [
  'Cougar',
  'HyperX',
  'Razer',
  'MSI',
  'Corsair',
  'ZET',
];

export const typesLayout: string[] = [
  'механическая',
  'ножничная',
  'мембранная',
];

export const colorsEffectLayout: string[] = [
  'RGB',
  'многоцветная',
  'красная',
];